---

- hosts: all
  become: true
  tasks:
  - name: Install Debian Packages
    apt:
      name:
        - libsqlite3-dev
        - libxml2-dev
        - zlib1g-dev
        - nginx
        - dehydrated
        - ruby
        - bundler
        - python-gdal
      state: present

  - name: "Ensure group radiodns-uk exists"
    group:
      name: radiodns-uk
      state: present

  - name: "Ensure user radiodns-uk exists"
    user:
      name: radiodns-uk
      comment: 'RadioDNS.uk'
      group: radiodns-uk
      shell: /bin/bash
      createhome: yes
      home: /home/radiodns-uk
      system: yes

  - name: 'Set permissions for .ssh'
    file:
      path: /home/radiodns-uk/.ssh
      state: directory
      owner: radiodns-uk
      group: radiodns-uk
      mode: 0755

  - name: 'Copy accross SSH authorized keys file'
    copy:
      src: authorized_keys
      dest: /home/radiodns-uk/.ssh/authorized_keys
      owner: radiodns-uk
      group: radiodns-uk
      mode: 0644

  - name: 'Create /srv/www/empty'
    file:
      path: /srv/www/empty
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: 'Create /srv/www/radiodns-uk'
    file:
      path: /srv/www/radiodns-uk
      state: directory
      owner: radiodns-uk
      group: radiodns-uk
      mode: 0755

  - name: 'Checkout code from github'
    become: yes
    become_user: radiodns-uk
    git:
      repo: 'https://github.com/njh/radiodns-uk.git'
      dest: /srv/www/radiodns-uk
    notify:
    - 'Restart Ruby App'

  - name: 'Ensure ruby bundle is up to date'
    become: yes
    become_user: radiodns-uk
    bundler:
      state: present
      chdir: /srv/www/radiodns-uk
      exclude_groups: development
      deployment_mode: yes
    notify:
    - 'Restart Ruby App'

  - name: 'Install systemd service file'
    copy:
      src: radiodns-uk.service
      dest: /etc/systemd/system/radiodns-uk.service

  - name: 'Start systemd service for web app'
    systemd:
      state: started
      name: radiodns-uk
      daemon_reload: yes

  - name: 'Download dhparam file from Mozilla'
    get_url:
      url: https://ssl-config.mozilla.org/ffdhe2048.txt
      dest: /etc/nginx/dhparam.txt
      mode: '0644'

  - name: 'Copy over modern SSL nginx settings'
    copy:
      src: modern-ssl.inc
      dest: /etc/nginx/conf.d/modern-ssl.inc
      mode: '0644'
    notify:
    - 'Restart Nginx'

  - name: 'Copy accross Nginx configuration file'
    copy:
      src: nginx.conf
      dest: /etc/nginx/sites-available/radiodns-uk
    notify:
    - 'Restart Nginx'

  - name: 'Enable Nginx configuration file'
    file:
      src: /etc/nginx/sites-available/radiodns-uk
      dest: /etc/nginx/sites-enabled/radiodns-uk
      state: link
    notify:
    - 'Restart Nginx'

  - name: "Ensure that dehydrated's domains.txt exists"
    file:
      path: /etc/dehydrated/domains.txt
      state: file
      owner: root
      group: root
      mode: 0644

  - name: 'Give dehydrated a contact email address'
    copy:
      content: "CONTACT_EMAIL=njh@aelius.com\n"
      dest: /etc/dehydrated/conf.d/contact.sh

  - name: "Add domains to dehydrated's domains.txt"
    lineinfile:
      path: /etc/dehydrated/domains.txt
      line: "{{ item }}"
    with_items:
      - "origin.radiodns.uk"
      - "redirect.radiodns.uk"
    notify:
      - 'Run dehydrated'

  handlers:
  - name: 'Restart Nginx'
    become: true
    service: name=nginx state=restarted
  - name: 'Run dehydrated'
    command: dehydrated -c
  - name: 'Restart Ruby App'
    become: true
    service: name=radiodns-uk state=restarted
